### ISSUE TITLE
Classes aded to the component are not rendered

### ISSUE THREAD

**Issue by LeCoupa** [achwilko/vue-material-icon#3]
```pug
icon(
    name="close"
    class="added-class-1 added-class-2"
)
```

renders:

```html
<span data-v-64e3f614="" class="material-icon" style="font-size: 24px;">
  close
</span>
```

should render:

```html
<span data-v-64e3f614="" class="material-icon added-class-1 added-class-2" style="font-size: 24px;">
  close
</span>
```

**Comment by achwilko** [comment]
Hi @LeCoupa 

Thanks for using the package. It's not a bug, it's a feature :) The problem is with "functional" approach:
https://vuejs.org/v2/guide/render-function.html#Functional-Components

I will update component to get non-functional approach and inherit HTML classes as you wish (might be useful also for others).

**Comment by LeCoupa** [comment]
Thanks a lot :-)

**Comment by LeCoupa** [comment]
Nothing new here? :)
